export const IMAGE = {
  loginBG: require('./loginBg.png'),
  Email: require('./message.png'),
  Password: require('./lock.png'),
  User: require('./user.png'),
  Delete: require('./Delete.png'),
  ForgetPassword: require('./fgPassword.png'),
  Reset: require('./reset.png'),
  Verification: require('./verification.png'),
  Right: require('./right.png'),
  GreenLock: require('./greenlock.png'),
  Greenkey: require('./greenkey.png'),
  Greenmessage: require('./greenMessage.png'),
  HomeNav: require('./homeNav.png'),
  StarNav: require('./Star.png'),
  ShoppingNav: require('./shopping.png'),
  UserNav: require('./userNav.png'),
  Filter: require('./filter.png'),
  SideBar: require('./sideBar.png'),
  Search: require('./search.png'),
  Header: require('./header.png'),
  Logo: require('./Logo.png'),
  VegOne: require('./VegOne.png'),
  VegTwo: require('./VegTwo.png'),
  VegThree: require('./VegThree.png'),
  CaneOne: require('./CaneOne.png'),
  CaneTwo: require('./CaneTwo.png'),
  CaneThree: require('./CaneThree.png'),
  UserSideBar: require('./userSidebar.png'),
  Manage: require('./setting.png'),
  Privacy: require('./privacy.png'),
  MyOrder: require('./myOrder.png'),
  Logout: require('./logout.png'),
  Setting: require('./settings.png'),
  Man: require('./man.png'),
  ActiveUser: require('./ActiveUser.png'),
  ActivePrivacy: require('./ActivePrivacy.png'),
  ActiveHome: require('./ActiveHome.png'),
  Back: require('./Back.png'),
  plus_icon: require('./plus_icon.png'),
  Edit: require('./edit.png'),
  Camera: require('./camera.png'),
  Rating: require('./starone.png'),
  BankIcon: require('./bank.png'),
  Arrow: require('./greenArrow.png'),
  OrderConfirm: require('./orderConfirm.png'),
  Share: require('./share.png'),
  Like: require('./Like.png'),
  Add: require('./add.png'),
  Remove: require('./remove.png'),
  Activelike: require('./activelike.png'),
  Visa: require('./visa.png'),
  Show: require('./Show.png'),
  ArrowBack: require('./arrowBack.png'),
  OnBoardingFirst: require('./onBoardingFirst.png'),
  OnBoardingSecond: require('./onBoardingSecond.png'),
  OnBoardingThird: require('./onBoardingThird.png'),
  ClosedEye: require('./closeeye.png'),
  Scan: require('./Scan.png'),
  DropDown: require('./DropDown.png'),
  AddGreenCircle: require('./AddGreenCircle.png'),
  AddItem_1: require('./AddItem_1.png'),
  Transactions: require('./Transaction.png'),
  ManageOrder: require('./ManageOrders.png'),
  AddItem: require('./addItem.png'),
  ThreeDots: require('./threedots.png'),
  newFilter: require('./new_filter.png'),
  Checkbox: require('./Checkbox.png'),
  Checkboxoff: require('./checkboxoff.png'),
  Emptyfavorite: require('./FavoriteEmptyImage.png'),
  EmptyCart: require('./EmptyCart.png'),
  EditAccount: require('./edit_account.png'),
  right_arrow: require('./right_arrow.png'),
  shop_vehicle: require('./shop_vehicle.png'),
  delivery: require('./delivery.png'),
  calendar: require('./calendar.png'),
  home_delivery: require('./home_delivery.png'),
  arrow_up: require('./arrow_up.png'),
  arrow_down: require('./arrow_down.png'),
  atoz: require('./atoz.png'),
  liked: require('./liked.png'),
  can_image: require('./can_image.png'),
  manprofile: require('./manprofile.png'),
  manbackground: require('./manbackground.png'),
  popuprightgreen: require('./rightGreenpopup.png'),
  mismatchpopup: require('./mismatchpopup.png'),
  logoutpopup: require('./logoutpopup.png'),
  Errorpopup: require('./Error.png'),
  crosspopup: require('./cross.png'),
  refresh: require('./refresh.png'),
  bin: require('./bin.png'),
  upload: require('./upload.png'),
  editCard: require('./editCard.png'),
  filtersaller: require('./filtersaller.png'),
  otp_icon: require('./otpVerify.png'),
};
export const COLORS = {
  Green: '#56AB2F',
  Black: '#000000',
};

export const Images = {
  loginBG: require('./loginBg.png'),
  email: require('./message.png'),
  password: require('./lock.png'),
  user: require('./user.png'),
  delete: require('./Delete.png'),
  forgetPassword: require('./fgPassword.png'),
  show: require('./Show.png'),
  closedEye: require('./closeeye.png'),
  greenMessage: require('./greenMessage.png'),
  logo: require('./Logo.png'),
  onBoardingFirst: require('./onBoardingFirst.png'),
  onBoardingSecond: require('./onBoardingSecond.png'),
  onBoardingThird: require('./onBoardingThird.png'),
  add: require('./add.png'),
  header: require('./header.png'),
  man: require('./man.png'),
  homeNav: require('./homeNav.png'),
  activeHome: require('./ActiveHome.png'),
  userSideBar: require('./userSidebar.png'),
  activeUser: require('./ActiveUser.png'),
  manage: require('./setting.png'),
  privacy: require('./privacy.png'),
  myOrder: require('./myOrder.png'),
  logout: require('./logout.png'),
  setting: require('./settings.png'),
  activePrivacy: require('./ActivePrivacy.png'),
  back: require('./Back.png'),
  share: require('./share.png'),
  editAccount: require('./edit_account.png'),
  rightArrow: require('./right_arrow.png'),
  reset: require('./reset.png'),
  camera: require('./camera.png'),
  greenLock: require('./greenlock.png'),
  otpIcon: require('./otpVerify.png'),
  sideBar: require('./sideBar.png'),
  emptyFavorite: require('./FavoriteEmptyImage.png'),
  refresh: require('./refresh.png'),
  scan: require('./Scan.png'),
  addItem: require('./addItem.png'),
  search: require('./search.png'),
  filterSeller: require('./filtersaller.png'),
  filter: require('./filter.png'),
  upload: require('./upload.png'),
  bin: require('./bin.png'),
  editCard: require('./editCard.png'),
  liked: require('./liked.png'),
  like: require('./Like.png'),
  addGreenCircle: require('./AddGreenCircle.png'),
  rating: require('./starone.png'),
  checkbox: require('./Checkbox.png'),
  checkBoxOff: require('./checkboxoff.png'),
};

export const TEXT = {
  HeaderText: 'Find Good Food For A Health Body',
  setPassword: 'Awesome! You’ve successfully updated your password.',
  resetText:
    'Please make sure your new password must be different from previously used password.',
  verificationText:
    'We have sent a password recovery instruction to your registered email.',
  ForgetText:
    'Enter the email associated with your account and we’ll send an email instruction to reset your password.',
  orderConfirm:
    'We will send order details and invoice on your contact no. and registered email.',
  ProductText:
    'Our recipe stars navy beans with a rich sauce of tasty molasses, blended with brown sugar, pork and our own blend of spices.',
  creditCardText:
    'We will send you an order details to your email after the successfull payment',
  SlidFirst:
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
  SlidSecond:
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
  SlidThird:
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
  PrivacyPolicy1:
    'This Privacy Policy will inform you about the types of personal data we collect, the purposes for which we use the data, the ways in which the data is handled and your rights with regard to your personal data. Furthermore, this Privacy Policy is intended to satisfy the obligation of transparency under the EU General Data Protection Regulation 2016/679  and the laws implementing GDPR.',
  PrivacyPolicy2:
    'For the purpose of this Privacy Policy the Data Controller of personal data is Wasai LLC and our contact details are set out in the Contact section at the end of this Privacy Policy. Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed.',
  PrivacyPolicy3:
    'We may change this Privacy Policy from time to time. If we decide to change this Privacy Policy, we will inform you by posting the revised Privacy Policy on the Site. Those changes will go into effect on the  date shown at the end of this Privacy Policy. By continuing to use the Site or Services, you consent to the revised Privacy Policy. We encourage you to periodically review the Privacy Policy for the latest information on our privacy practices.',
  PrivacyPolicy4:
    'If you have any questions or if you would like to contact us about our processing of your personal information, including exercising your rights as outlined above, please contact us by any of the methods below. When you contact us, we will ask you to verify your identity.',
};
